<a href="https://colab.research.google.com/github/AloneMusk/DeepLearning_with_PyTorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR MATH OPERATIONS


*   Add, Sub, Mul, Divide, Remainders, Exponents
*   Shorthand, Longhand
*   Reassignment

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
#Addition - shorthand
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
#Addition - longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
#Subtract - shorthand
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
#subtract - longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
#Mul
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
#Division
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
#Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
#remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
#Exponents/power
torch.pow(tensor_a, tensor_b) #a^b

tensor([    1,    64,  2187, 65536])

In [ ]:
#Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a

tensor([1, 2, 3, 4])

In [ ]:
tensor_a.add_(tensor_b) #underscore is what leads to reassignment, else it is just the same as cell 16
tensor_a

tensor([ 6,  8, 10, 12])